// <auto-generated />
namespace AdoptMe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameAdoptionAgencies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameAdoptionAgencies));
        
        string IMigrationMetadata.Id
        {
            get { return "201710061159291_Rename-Adoption-Agencies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
